### ISSUE TITLE
keyerror when running run.sh

### ISSUE THREAD

**Issue by HaoruiZhang** [tanghaibao/goatools#135]
Hi,
I have been testing the script "run.sh", but I encountered  some problems and I don't know how to solve:
======================================
$ sh run.sh 
select the test from below
1) Test enrichment	       3) Test mapslim
2) Test plotting go terms      4) Test mapslim on assocation
#? 1
Traceback (most recent call last):
  File "scripts/find_enrichment.py", line 44, in <module>
    main()
  File "scripts/find_enrichment.py", line 31, in main
    obj = GoeaCliFnc(GoeaCliArgs().args)
  File "/anaconda3/lib/python3.5/site-packages/goatools/cli/find_enrichment.py", line 215, in __init__
    self.godag = GODag(obo_file=self.args.obo, optional_attrs=godag_optional_attrs)
  File "/anaconda3/lib/python3.5/site-packages/goatools/obo_parser.py", line 285, in __init__
    self.version = self.load_obo_file(obo_file, optional_attrs, load_obsolete, prt)
  File "/anaconda3/lib/python3.5/site-packages/goatools/obo_parser.py", line 306, in load_obo_file
    self._populate_terms(reader.optobj)
  File "/anaconda3/lib/python3.5/site-packages/goatools/obo_parser.py", line 336, in _populate_terms
    rec.parents = set([self[goid] for goid in rec._parents])
  File "/anaconda3/lib/python3.5/site-packages/goatools/obo_parser.py", line 336, in <listcomp>
    rec.parents = set([self[goid] for goid in rec._parents])
KeyError: 'GO:0072337'
#? 2
Traceback (most recent call last):
  File "scripts/plot_go_term.py", line 48, in <module>
    g = GODag(obo_file)
  File "scripts/../goatools/obo_parser.py", line 285, in __init__
    self.version = self.load_obo_file(obo_file, optional_attrs, load_obsolete, prt)
  File "scripts/../goatools/obo_parser.py", line 306, in load_obo_file
    self._populate_terms(reader.optobj)
  File "scripts/../goatools/obo_parser.py", line 336, in _populate_terms
    rec.parents = set([self[goid] for goid in rec._parents])
  File "scripts/../goatools/obo_parser.py", line 336, in <listcomp>
    rec.parents = set([self[goid] for goid in rec._parents])
KeyError: 'GO:0045595'
#? 3 ...
=========================

Thanks!

**Comment by dvklopfenstein** [comment]
Hello, Thank you for your interest in GOATOOLS and thank you for taking the time to write us.

I suspect that the go-basic.obo file had an incomplete download. How big is it? The 2019-07-01 release should be about 30Mb:
```
$ l -lh go-basic.obo
-rwxr-xr-x+ 1 note2 note2 30M Jul 25 18:09 go-basic.obo
```

What is the size your your go-basic.obo?

Try downloading the go-basic.obo file again:
```
$ wget http://geneontology.org/ontology/go-basic.obo
```
