### ISSUE TITLE
SystemExit (from goatools.anno.init.reader_gaf)

### ISSUE THREAD

**Issue by cross12tamu** [tanghaibao/goatools#149]
Howdy,

Per usual, just need to thank you for the great tool. It is really __really__ helpful.

Regardless, I'm getting an odd error when parsing the 'goa_uniprot_all_noiea.gaf' from http://current.geneontology.org/annotations/index.html

The errors ends up being a SystemExit error with a failing in the goatools.anno.init.reader_gaf. I would not expect to run into an error here, but obviously I am. 

I initially get this popping up in the console: 

```python
[autoreload of goatools.anno.init.reader_gaf failed: Traceback (most recent call last):
  File "/home/crr/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/home/crr/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 450, in superreload
    update_generic(old_obj, new_obj)
  File "/home/crr/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 387, in update_generic
    update(a, b)
  File "/home/crr/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 357, in update_class
    update_instances(old, new)
  File "/home/crr/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 317, in update_instances
    update_instances(old, new, obj, visited)
  File "/home/crr/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 312, in update_instances
    update_instances(old, new, obj.__dict__, visited)
  File "/home/crr/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 317, in update_instances
    update_instances(old, new, obj, visited)
  File "/home/crr/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 312, in update_instances
    update_instances(old, new, obj.__dict__, visited)
  File "/home/crr/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 317, in update_instances
    update_instances(old, new, obj, visited)
  File "/home/crr/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 312, in update_instances
    update_instances(old, new, obj.__dict__, visited)
RecursionError: maximum recursion depth exceeded while calling a Python object
]
```

The script proceeds...

loads obo

does a quick calculation on a dataframe that I have in the script 

and then the final error

```python
Traceback (most recent call last):
  File "/home/crr/anaconda3/lib/python3.7/site-packages/goatools-0.9.9-py3.7.egg/goatools/anno/init/reader_gaf.py", line 86, in _read_gaf_nts
    datobj = GafData(ver, allow_missing_symbol)
  File "/home/crr/anaconda3/lib/python3.7/site-packages/goatools-0.9.9-py3.7.egg/goatools/anno/init/reader_gaf.py", line 166, in __init__
    self.is_long = ver[0] == '2'
TypeError: 'NoneType' object is not subscriptable

  **FATAL-gaf: 'NoneType' object is not subscriptable

**FATAL-gaf: /home/crr/path/to/file/goa_uniprot_all_noiea.gaf[1]:
UniProtKB       A0A009IHW8      J512_3302               GO:0003953      PMID:29395922   IDA             F       TIR domain-containing protein   J512_3302       protein taxon:1310613   20191128        UniProt         
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

/home/crr/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
```

___I'm wondering if there's anything that I can do, or if this is some unseen bug.___
Lastly, my goatools version is:
```python
goatools.__version__
```
> Out[11]: 'v0.9.9'

Thanks in advance!

**Comment by dvklopfenstein** [comment]
Thank you so much for opening this issue and for your feedback and support.

I have an important meeting tomorrow, but can look at this issue Thursday, Jan 14.

**Comment by tanghaibao** [comment]
This should have been fixed in recent versions of `goatools`.
