### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by chestnzu1** [tanghaibao/goatools#170]
Hello:
   I was trying to run the example file 'plot_go_term.py' in pycharm.  but I got an AttributeError :
Traceback (most recent call last):
  File "plot_go_term.py", line 59, in <module>
    draw_children=opts.draw_children)
  File "C:\ProgramData\Miniconda3\lib\site-packages\goatools\obo_parser.py", line 594, in draw_lineage
    obj = nx.from_agraph(grph) if engine == "pygraphviz" else nx.from_pydot(grph)
AttributeError: module 'networkx' has no attribute 'from_agraph'
Can anyone tell me how to fix this?
thanks

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOATOOLS and thank you for taking your time to write to us.

Please try scripts/go_plot.py, rather than scripts/plot_go_term.py.

The script, go_plot, uses our newer code has more features, like being able to color your GO terms. 

Graphviz's `dot` program is used in go_plot. You can check to be sure that you have Graphviz's dot program installed on your machine by doing:

```
$ dot -?
Usage: dot [-Vv?] [-(GNE)name=val] [-(KTlso)<val>] <dot files>
(additional options for neato)    [-x] [-n<v>]
(additional options for fdp)      [-L(gO)] [-L(nUCT)<val>]
(additional options for memtest)  [-m<v>]
(additional options for config)  [-cv]

 -V          - Print version and exit
 -v          - Enable verbose mode
 -Gname=val  - Set graph attribute 'name' to 'val'
 -Nname=val  - Set node attribute 'name' to 'val'
 -Ename=val  - Set edge attribute 'name' to 'val'
 -Tv         - Set output format to 'v'
 -Kv         - Set layout engine to 'v' (overrides default based on command name)
 -lv         - Use external library 'v'
 -ofile      - Write output to 'file'
 -O          - Automatically generate an output filename based on the input filename with a .'format' appended. (Causes all -ofile options to be ignored.)
 -P          - Internally generate a graph of the current plugins.
 -q[l]       - Set level of message suppression (=1)
 -s[v]       - Scale input by 'v' (=72)
 -y          - Invert y coordinate in output

 -n[v]       - No layout mode 'v' (=1)
 -x          - Reduce graph

 -Lg         - Don't use grid
 -LO         - Use old attractive force
 -Ln<i>      - Set number of iterations to i
 -LU<i>      - Set unscaled factor to i
 -LC<v>      - Set overlap expansion factor to v
 -LT[*]<v>   - Set temperature (temperature factor) to v

 -m          - Memory test (Observe no growth with top. Kill when done.)
 -m[v]       - Memory test - v iterations.

 -c          - Configure plugins (Writes $prefix/lib/graphviz/config
               with available plugin information.  Needs write privilege.)
 -?          - Print usage and exit
```

**Comment by chestnzu1** [comment]
Thanks for your reply, I tried to use scripts/go_plot.py as you said, but I still can not generate the graph.
My first trial is python scripts\go_plot.py GO:0003304 -o file.png, then I get
```
go-basic.obo: fmt(1.2) rel(2020-06-01) 47,233 GO Terms
 GoSubDag:   2 sources in  12 GOs rcnt(True). 0 alt GO IDs
 GoSubDag: namedtuple fields: NS level depth GO alt GO_name dcnt D1 id
 GoSubDag: relationships: set()
        GO:0008150  # BP 29111 L00 D00       biological_process
#f1fbfd GO:0032502  # BP  3225 L01 D01 A     developmental process
        GO:0009653  # BP   703 L02 D02 A     anatomical structure morphogenesis
        GO:0048598  # BP   109 L03 D03 A     embryonic morphogenesis
        GO:0035239  # BP    89 L03 D03 A     tube morphogenesis
(env) E:\PHD\goatools-master>python scripts\go_plot.py GO:0003304 --outfile=<file.png>
The syntax of the command is incorrect.

(env) E:\PHD\goatools-master>python scripts\go_plot.py GO:0003304 -o file.png
go-basic.obo: fmt(1.2) rel(2020-06-01) 47,233 GO Terms
 GoSubDag:   1 sources in   7 GOs rcnt(True). 0 alt GO IDs
 GoSubDag: namedtuple fields: NS level depth GO alt GO_name dcnt D1 id
 GoSubDag: relationships: set()
        GO:0008150  # BP 29111 L00 D00       biological_process
#f1fbfd GO:0032502  # BP  3225 L01 D01 A     developmental process
        GO:0009653  # BP   703 L02 D02 A     anatomical structure morphogenesis
        GO:0048729  # BP   197 L03 D03 A     tissue morphogenesis
        GO:0002009  # BP   148 L04 D04 A     morphogenesis of an epithelium
        GO:0060571  # BP    15 L05 D05 A     morphogenesis of an epithelial fold
#ffffe4 GO:0003304  # BP     0 L06 D06 A     myocardial epithelial involution involved in heart jogging
"dot" with args ['-Tpng', 'C:\\Users\\chest\\AppData\\Local\\Temp\\tmp0h8h_cv6'] returned code: 1

stdout, stderr:
 b''
b'Format: "png" not recognized. Use one of:\r\n'

Traceback (most recent call last):
  File "scripts\go_plot.py", line 16, in <module>
    run()
  File "scripts\go_plot.py", line 12, in run
    PlotCli().cli()
  File "C:\ProgramData\Miniconda3\lib\site-packages\goatools\cli\gosubdag_plot.py", line 172, in cli
    self.plot(godag, kws_all)
  File "C:\ProgramData\Miniconda3\lib\site-packages\goatools\cli\gosubdag_plot.py", line 179, in plot
    objplt.plt_dag(fout_img)
  File "C:\ProgramData\Miniconda3\lib\site-packages\goatools\gosubdag\plot\gosubdag_plot.py", line 160, in plt_dag
    self._plt_pydot(fout_img)
  File "C:\ProgramData\Miniconda3\lib\site-packages\goatools\gosubdag\plot\gosubdag_plot.py", line 169, in _plt_pydot
    self.wr_pydot_dag(fout_img, dag)
  File "C:\ProgramData\Miniconda3\lib\site-packages\goatools\gosubdag\plot\gosubdag_plot.py", line 174, in wr_pydot_dag
    dag.write(fout_img, format=img_fmt)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pydot.py", line 1817, in write
    s = self.create(prog, format, encoding=encoding)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pydot.py", line 1945, in create
    assert process.returncode == 0, process.returncode
AssertionError: 1

```
Then I tried python scripts/go_plot.py GO:0003304 GO:0003146 -o heart_jogging_r1.png
and I get the same output. 
I also tried some code [in](https://github.com/tanghaibao/goatools/blob/master/doc/md/README_go_plot.md#plot-the-go-hierarchy-with-go_plotpy) but I didn't get the same result as the graph shows.

Thanks in advance...

**Comment by dvklopfenstein** [comment]
It looks like you are using the Windows operating system.

Try running the command from a command shell from Cygwin, which can be downloaded from: https://www.cygwin.com/,.

Cygwin gives you that Linux-like feel while running native Windows programs.

Download go-basic.obo with:    
```$ wget http://geneontology.org/ontology/go-basic.obo```

Here is what you should see when creating the plot:

```
$ scripts/go_plot.py GO:0003304 -o file.png
go-basic.obo: fmt(1.2) rel(2020-06-01) 47,233 GO Terms
 GoSubDag:   1 sources in   7 GOs rcnt(True). 0 alt GO IDs
 GoSubDag: namedtuple fields: NS level depth GO alt GO_name dcnt D1 id
 GoSubDag: relationships: set([])
        GO:0008150  # BP 29111 L00 D00       biological_process
#f1fbfd GO:0032502  # BP  3225 L01 D01 A     developmental process
        GO:0009653  # BP   703 L02 D02 A     anatomical structure morphogenesis
        GO:0048729  # BP   197 L03 D03 A     tissue morphogenesis
        GO:0002009  # BP   148 L04 D04 A     morphogenesis of an epithelium
        GO:0060571  # BP    15 L05 D05 A     morphogenesis of an epithelial fold
#ffffe4 GO:0003304  # BP     0 L06 D06 A     myocardial epithelial involution involved in heart jogging
    1 usr   7 GOs  WROTE: file.png
```

**Comment by chestnzu1** [comment]
Thanks, I made it.
