### ISSUE TITLE
connection refused in download_ncbi_associations

### ISSUE THREAD

**Issue by ernestmordret** [tanghaibao/goatools#198]
Hi!

thank you so much for developing this tool, it seems to be exactly what I'm looking for. However, I'm trying to run the following notebook :"Run a Gene Ontology Enrichment Analysis (GOEA)", and it seems that "download_ncbi_associations" is broken. Running the cell below spits an error message:

```
# Get ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/gene2go.gz
from goatools.base import download_ncbi_associations
fin_gene2go = download_ncbi_associations()
```

```
FTP RETR ftp.ncbi.nlm.nih.gov gene/DATA gene2go.gz -> gene2go.gz
Traceback (most recent call last):
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/goatools/base.py", line 219, in dnld_file
    rsp = http_get(src_ftp, dst_wget) if src_ftp[:4] == 'http' else ftp_get(src_ftp, dst_wget)
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/goatools/base.py", line 202, in ftp_get
    ftp.retrbinary(cmd, open(fout, 'wb').write)  #           /usr/home/gene2go.gz
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/ftplib.py", line 425, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/ftplib.py", line 382, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/ftplib.py", line 343, in ntransfercmd
    conn = socket.create_connection((host, port), self.timeout,
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
**FATAL cmd: wget(ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/gene2go.gz out=gene2go.gz)
**FATAL msg: [Errno 61] Connection refusedERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/goatools/base.py", line 219, in dnld_file
    rsp = http_get(src_ftp, dst_wget) if src_ftp[:4] == 'http' else ftp_get(src_ftp, dst_wget)
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/goatools/base.py", line 202, in ftp_get
    ftp.retrbinary(cmd, open(fout, 'wb').write)  #           /usr/home/gene2go.gz
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/ftplib.py", line 425, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/ftplib.py", line 382, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/ftplib.py", line 343, in ntransfercmd
    conn = socket.create_connection((host, port), self.timeout,
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-fa8d3bdfc016>", line 3, in <module>
    fin_gene2go = download_ncbi_associations()
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/goatools/base.py", line 133, in download_ncbi_associations
    dnld_file(file_remote, gene2go, prt, loading_bar)
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/goatools/base.py", line 229, in dnld_file
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1170, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Users/ernestmordret/opt/anaconda3/envs/py3_goa/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
~/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/goatools/base.py in dnld_file(src_ftp, dst_file, prt, loading_bar)
    218         #### wget.download(src_ftp, out=dst_wget, bar=loading_bar)
--> 219         rsp = http_get(src_ftp, dst_wget) if src_ftp[:4] == 'http' else ftp_get(src_ftp, dst_wget)
    220         if do_gunzip:

~/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/goatools/base.py in ftp_get(fin_src, fout)
    201     cmd = 'RETR {F}'.format(F=fin_ftp)   #                   gene2go.gz
--> 202     ftp.retrbinary(cmd, open(fout, 'wb').write)  #           /usr/home/gene2go.gz
    203     ftp.quit()

~/opt/anaconda3/envs/py3_goa/lib/python3.8/ftplib.py in retrbinary(self, cmd, callback, blocksize, rest)
    424         self.voidcmd('TYPE I')
--> 425         with self.transfercmd(cmd, rest) as conn:
    426             while 1:

~/opt/anaconda3/envs/py3_goa/lib/python3.8/ftplib.py in transfercmd(self, cmd, rest)
    381         """Like ntransfercmd() but returns only the socket."""
--> 382         return self.ntransfercmd(cmd, rest)[0]
    383 

~/opt/anaconda3/envs/py3_goa/lib/python3.8/ftplib.py in ntransfercmd(self, cmd, rest)
    342             host, port = self.makepasv()
--> 343             conn = socket.create_connection((host, port), self.timeout,
    344                                             source_address=self.source_address)

~/opt/anaconda3/envs/py3_goa/lib/python3.8/socket.py in create_connection(address, timeout, source_address)
    807         try:
--> 808             raise err
    809         finally:

~/opt/anaconda3/envs/py3_goa/lib/python3.8/socket.py in create_connection(address, timeout, source_address)
    795                 sock.bind(source_address)
--> 796             sock.connect(sa)
    797             # Break explicitly a reference cycle

ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

<ipython-input-20-fa8d3bdfc016> in <module>
      2 from goatools.base import download_ncbi_associations
----> 3 fin_gene2go = download_ncbi_associations()

~/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/goatools/base.py in download_ncbi_associations(gene2go, prt, loading_bar)
    132             GZ=os.path.basename(gzip_file))
--> 133         dnld_file(file_remote, gene2go, prt, loading_bar)
    134     else:

~/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/goatools/base.py in dnld_file(src_ftp, dst_file, prt, loading_bar)
    228         sys.stderr.write("**FATAL msg: {ERR}".format(ERR=str(errmsg)))
--> 229         sys.exit(1)
    230 

SystemExit: 1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

~/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2036                     stb = ['An exception has occurred, use %tb to see '
   2037                            'the full traceback.\n']
-> 2038                     stb.extend(self.InteractiveTB.get_exception_only(etype,
   2039                                                                      value))
   2040                 else:

~/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/IPython/core/ultratb.py in get_exception_only(self, etype, value)
    821         value : exception value
    822         """
--> 823         return ListTB.structured_traceback(self, etype, value)
    824 
    825     def show_exception_only(self, etype, evalue):

~/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, context)
    696             chained_exceptions_tb_offset = 0
    697             out_list = (
--> 698                 self.structured_traceback(
    699                     etype, evalue, (etb, chained_exc_ids),
    700                     chained_exceptions_tb_offset, context)

~/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1434         else:
   1435             self.tb = tb
-> 1436         return FormattedTB.structured_traceback(
   1437             self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1438 

~/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1334         if mode in self.verbose_modes:
   1335             # Verbose modes need a full traceback
-> 1336             return VerboseTB.structured_traceback(
   1337                 self, etype, value, tb, tb_offset, number_of_lines_of_context
   1338             )

~/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1191         """Return a nice text document describing the traceback."""
   1192 
-> 1193         formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
   1194                                                                tb_offset)
   1195 

~/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/IPython/core/ultratb.py in format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
   1149 
   1150 
-> 1151         last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
   1152 
   1153         frames = self.format_records(records, last_unique, recursion_repeat)

~/opt/anaconda3/envs/py3_goa/lib/python3.8/site-packages/IPython/core/ultratb.py in find_recursion(etype, value, records)
    449     # first frame (from in to out) that looks different.
    450     if not is_recursion_error(etype, value, records):
--> 451         return len(records), 0
    452 
    453     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()
```

Do you have any clue of what might be causing it?
Best,

Ernest

**Comment by tanghaibao** [comment]
@ernestmordret 

This is probably too late to be useful - but I just tried the same and it worked (although the downloading is a bit slow due to the large file size). Is this still an issue for you?
