### ISSUE TITLE
Error: Unicode Decode Error

### ISSUE THREAD

**Issue by yb520abab** [tanghaibao/goatools#295]
Hi,

Thank you for providing such a great tool! I encountered a "Unicode Decode Error: 'ascii' codec can't decode byte 0xe2 in position 1103: ordinal not in range(128)". I converted all my gene symbols into gene IDs, and I converted them into UTF-8 format. The format of gene IDs look right to me. The error asked me to trace back to the file "find_enrichment.py" but I don't have the access to edit the script or other scripts. Did anyone else also encounter the similar problem? Many thanks!

**Comment by yb520abab** [comment]
@tanghaibao 
Hi, I checked my files and there isn't any non-standard character 'â' in the files. Here's the traceback message: Traceback (most recent call last):
  File "scripts/find_enrichment.py", line 44, in <module>
    main()
  File "scripts/find_enrichment.py", line 31, in main
    obj = GoeaCliFnc(GoeaCliArgs().args)
  File "/u/home/y/yebi24/.conda/envs/be298/lib/python3.6/site-packages/goatools/cli/find_enrichment.py", line 232, in __init__
    _study, _pop = self.rd_files(*self.args.filenames[:2])
  File "/u/home/y/yebi24/.conda/envs/be298/lib/python3.6/site-packages/goatools/cli/find_enrichment.py", line 416, in rd_files
    study, pop = self._read_geneset(study_fn, pop_fn)
  File "/u/home/y/yebi24/.conda/envs/be298/lib/python3.6/site-packages/goatools/cli/find_enrichment.py", line 424, in _read_geneset
    study = frozenset(_.strip() for _ in open(study_fn) if _.strip())
  File "/u/home/y/yebi24/.conda/envs/be298/lib/python3.6/site-packages/goatools/cli/find_enrichment.py", line 424, in <genexpr>
    study = frozenset(_.strip() for _ in open(study_fn) if _.strip())
  File "/u/home/y/yebi24/.conda/envs/be298/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
Many thanks!
