### ISSUE TITLE
Can't `pip install goatoools` on version 0.6.9

### ISSUE THREAD

**Issue by yunesj** [tanghaibao/goatools#69]
Can't `pip install goatools` on version 0.6.9 in new virtualenv. `pip install goatools==0.6.5` works fine.

```
(venv) jeff$ pip install goatools
Collecting goatools
  Using cached goatools-0.6.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jw/23sjzsn97lz8qj3kp4bg4pw00000gn/T/pip-build-tHhzLf/goatools/setup.py", line 19, in <module>
        open('requirements.txt').readlines()]
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jw/23sjzsn97lz8qj3kp4bg4pw00000gn/T/pip-build-tHhzLf/goatools/
```

```
(venv) jeff$ pip install goatools==0.6.5
Collecting goatools==0.6.5
Collecting fisher (from goatools==0.6.5)
  Using cached fisher-0.1.4.tar.gz
Collecting xlsxwriter (from goatools==0.6.5)
  Using cached XlsxWriter-0.9.3-py2.py3-none-any.whl
Collecting wget (from goatools==0.6.5)
Collecting statsmodels (from goatools==0.6.5)
  Using cached statsmodels-0.6.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Building wheels for collected packages: fisher
  Running setup.py bdist_wheel for fisher ... done
  Stored in directory: /Users/jeff/Library/Caches/pip/wheels/94/70/27/f3e07047ba539a9c8a24c5738dad745c6fe3f1d76aa714ed83
Successfully built fisher
Installing collected packages: fisher, xlsxwriter, wget, statsmodels, goatools
Successfully installed fisher-0.1.4 goatools-0.6.5 statsmodels-0.6.1 wget-3.2 xlsxwriter-0.9.3
```

**Comment by dvklopfenstein** [comment]
@olgabot , Can you take a look at this?

**Comment by ehinderer** [comment]
I had the same issue with "requirements.txt." I was able to install version 0.6.9 like this:
`pip install git+git://github.com/tanghaibao/goatools.git`

**Comment by dvklopfenstein** [comment]
@tanghaibao I think we just need a new PyPI version now with the new updates and then we can close this.

**Comment by dvklopfenstein** [comment]
Thank you, olgabot, for your speedy and detailed response. And thank you yunesj for calling attention to this issue.

**Comment by dvklopfenstein** [comment]
And thank you @ehinderer for the workaround while we make the fix.
